name: Pull Request Check

on:
  pull_request:
    branches:
      - main

jobs:
  pull_request_check:
    name: Pull Request Check
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          run_install: true

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test

      - name: Build
        run: pnpm build
